"""All ORM models — imported here so Alembic autogenerate and Base.metadata see every table."""
from app.db.base import Base
from app.models.audit import AuditLog
from app.models.case_law import Citation, Court, CourtDecision, VerificationStatus
from app.models.contracts import (
    AlternativeClause,
    Contract,
    ContractClause,
    ContractObligation,
    ContractParty,
    ContractRecommendation,
    ContractReview,
    ContractRisk,
    ContractVersion,
    RedlineChange,
)
from app.models.embedding_chunk import EmbeddingChunk
from app.models.legal_knowledge import Law, LawVersion, LegalDocument, LegalSource
from app.models.matters import (
    Case,
    CaseContradiction,
    CaseDocument,
    CaseDocumentRole,
    CaseEvent,
    CaseFact,
    CaseFactEvidence,
    CaseParty,
    ContradictionType,
    DateType,
    Document,
    DocumentChunk,
    DocumentStatus,
    Evidence,
    FactStatus,
    FactType,
    LegalIssue,
    LegalResearchReport,
    LegalRisk,
    PartyType,
    ProceduralRole,
)
from app.models.organization import Organization, Role, User, Workspace, WorkspaceMembership
from app.models.source_document import SourceDocument

__all__ = [
    "Base",
    "Organization",
    "Role",
    "User",
    "Workspace",
    "WorkspaceMembership",
    "LegalSource",
    "LegalDocument",
    "Law",
    "LawVersion",
    "Court",
    "CourtDecision",
    "Citation",
    "VerificationStatus",
    "Case",
    "Document",
    "DocumentChunk",
    "DocumentStatus",
    "Evidence",
    "LegalIssue",
    "LegalRisk",
    "LegalResearchReport",
    "AuditLog",
    "SourceDocument",
    "EmbeddingChunk",
    "Contract",
    "ContractVersion",
    "ContractParty",
    "ContractClause",
    "ContractObligation",
    "ContractRisk",
    "ContractRecommendation",
    "AlternativeClause",
    "RedlineChange",
    "ContractReview",
    "CaseParty",
    "PartyType",
    "ProceduralRole",
    "CaseDocument",
    "CaseDocumentRole",
    "CaseFact",
    "FactStatus",
    "FactType",
    "CaseFactEvidence",
    "CaseEvent",
    "DateType",
    "CaseContradiction",
    "ContradictionType",
]
